In [75]:
#Data Cleaning
import pandas as pd
df = pd.read_csv('unclean_data.csv')
df

,property_name,areaWithType,square_feet,transaction,status,floor,furnishing,facing,description,price_per_sqft,price
0,2 BHK Apartment for Sale in Dindoli Surat,Carpet Area,644 sqft,New Property,Poss. by Oct '24,5 out of 10,Unfurnished,West,"Luxury project with basement parking, Solar ro...","₹2,891 per sqft",₹33.8 Lac
1,2 BHK Apartment for Sale in Althan Surat,Super Area,1278 sqft,New Property,Poss. by Jan '26,6 out of 14,Unfurnished,South -West,2 And 3 BHK Luxurious Flat for Sell In New Alt...,"₹3,551 per sqft",₹45.4 Lac
2,2 BHK Apartment for Sale in Pal Gam Surat,Super Area,1173 sqft,Resale,Ready to Move,5 out of 13,Semi-Furnished,East,This affordable 2 BHK flat is situated along a...,"₹3,800 per sqft",₹44.6 Lac
3,2 BHK Apartment for Sale in Jahangirabad Surat,Carpet Area,700 sqft,New Property,Ready to Move,6 out of 14,Unfurnished,East,2 BHK Flat For sell IN Jahangirabad Prime Loca...,"₹3,966 per sqft",₹47 Lac
4,"2 BHK Apartment for Sale in Orchid Fantasia, P...",Super Area,1250 sqft,Orchid Fantasia,New Property,Unfurnished,2,2,"Multistorey Apartment for Sale in Palanpur, Su...","₹3,600 per sqft",₹45 Lac
...,...,...,...,...,...,...,...,...,...,...,...
4520,6 BHK Apartment for Sale in Millionaires Lifes...,Carpet Area,2000 sqft,New Property,Poss. by Dec '26,5 out of 12,Unfurnished,South - East,"Check out Millionaires Lifestyle in Vesu, one ...",NaN,Call for Price
4521,"4 BHK Apartment for Sale in Savan Superia, Alt...",Super Area,3600 sqft,New Property,Poss. by Dec '25,5 out of 16,Unfurnished,South - East,Superia is a premium residential project launc...,NaN,Call for Price
4522,5 BHK Apartment for Sale in Roongta Green Vall...,Carpet Area,2250 sqft,New Property,Poss. by Dec '25,7 out of 13,Unfurnished,North - East,"When it comes to beautiful homes, nothing beat...",NaN,Call for Price
4523,"6 BHK Apartment for Sale in Cellestial Dreams,...",Carpet Area,3450 sqft,New Property,Ready to Move,7 out of 18,Unfurnished,North - West,"DRB Ravani Cellestial Dreams in Vesu, Surat is...",NaN,Call for Price
4524,4 BHK Apartment for Sale in Roongta Green Vall...,Super Area,4500 sqft,New Property,Ready to Move,3 out of 12,Unfurnished,North,Roongta Green Valley is one of the popular res...,NaN,Call for Price

In [76]:
#check missing cells
df.isnull().sum()

property_name        0
areaWithType         0
square_feet          0
transaction        104
status               1
floor               45
furnishing         340
facing             589
description       1371
price_per_sqft     368
price                0
dtype: int64

In [77]:
#check non-empty cells
df.notnull().sum()

property_name     4525
areaWithType      4525
square_feet       4525
transaction       4421
status            4524
floor             4480
furnishing        4185
facing            3936
description       3154
price_per_sqft    4157
price             4525
dtype: int64

In [78]:
df.info() #view information about data

<class 'pandas.DataFrame'>
RangeIndex: 4525 entries, 0 to 4524
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   property_name   4525 non-null   str
 1   areaWithType    4525 non-null   str
 2   square_feet     4525 non-null   str
 3   transaction     4421 non-null   str
 4   status          4524 non-null   str
 5   floor           4480 non-null   str
 6   furnishing      4185 non-null   str
 7   facing          3936 non-null   str
 8   description     3154 non-null   str
 9   price_per_sqft  4157 non-null   str
 10  price           4525 non-null   str
dtypes: str(11)
memory usage: 389.0 KB

In [79]:
##view Duplicate Rows
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
4520    False
4521    False
4522    False
4523    False
4524    False
Length: 4525, dtype: bool

In [80]:
# df.dropna(axis= 1)

In [81]:
df.head(10)

,property_name,areaWithType,square_feet,transaction,status,floor,furnishing,facing,description,price_per_sqft,price
0,2 BHK Apartment for Sale in Dindoli Surat,Carpet Area,644 sqft,New Property,Poss. by Oct '24,5 out of 10,Unfurnished,West,"Luxury project with basement parking, Solar ro...","₹2,891 per sqft",₹33.8 Lac
1,2 BHK Apartment for Sale in Althan Surat,Super Area,1278 sqft,New Property,Poss. by Jan '26,6 out of 14,Unfurnished,South -West,2 And 3 BHK Luxurious Flat for Sell In New Alt...,"₹3,551 per sqft",₹45.4 Lac
2,2 BHK Apartment for Sale in Pal Gam Surat,Super Area,1173 sqft,Resale,Ready to Move,5 out of 13,Semi-Furnished,East,This affordable 2 BHK flat is situated along a...,"₹3,800 per sqft",₹44.6 Lac
3,2 BHK Apartment for Sale in Jahangirabad Surat,Carpet Area,700 sqft,New Property,Ready to Move,6 out of 14,Unfurnished,East,2 BHK Flat For sell IN Jahangirabad Prime Loca...,"₹3,966 per sqft",₹47 Lac
4,"2 BHK Apartment for Sale in Orchid Fantasia, P...",Super Area,1250 sqft,Orchid Fantasia,New Property,Unfurnished,2,2,"Multistorey Apartment for Sale in Palanpur, Su...","₹3,600 per sqft",₹45 Lac
5,"2 BHK Apartment for Sale in Anand Aspire, Jaha...",Super Area,1265 sqft,Unfurnished,Poss. by Dec '25,New Property,Anand Aspire,2,Multistorey Apartment for Sale in Jahangirabad...,"₹3,411 per sqft",₹43.2 Lac
6,3 BHK Villa for Sale in Dindoli Surat,Carpet Area,1404 sqft,Unfurnished,Poss. by Jun '24,New Property,East,Main Road,contraction,NaN,₹42.1 Lac
7,Office Space for Sale in Vesu Surat,Carpet Area,700 sqft,New Property,Poss. by Sep '25,7 out of 10,1,NaN,"best commercial for business ,investors ,busin...","₹3,392 per sqft",₹44.1 Lac
8,"2 BHK Apartment for Sale in Orchid Gardenia, P...",Super Area,1180 sqft,Orchid Gardenia,New Property,Unfurnished,2,2,"Multistorey Apartment for Sale in Palanpur, Su...","₹3,751 per sqft",₹44.3 Lac
9,2 BHK Apartment for Sale in Palanpur Surat,Carpet Area,720 sqft,New Property,Poss. by Dec '25,3 out of 14,Unfurnished,East,"Irrespective of the business branch, the our g...","₹3,200 per sqft",₹40 Lac

In [82]:
# df.dropna(inplace =True)

In [83]:
df.head(10)

,property_name,areaWithType,square_feet,transaction,status,floor,furnishing,facing,description,price_per_sqft,price
0,2 BHK Apartment for Sale in Dindoli Surat,Carpet Area,644 sqft,New Property,Poss. by Oct '24,5 out of 10,Unfurnished,West,"Luxury project with basement parking, Solar ro...","₹2,891 per sqft",₹33.8 Lac
1,2 BHK Apartment for Sale in Althan Surat,Super Area,1278 sqft,New Property,Poss. by Jan '26,6 out of 14,Unfurnished,South -West,2 And 3 BHK Luxurious Flat for Sell In New Alt...,"₹3,551 per sqft",₹45.4 Lac
2,2 BHK Apartment for Sale in Pal Gam Surat,Super Area,1173 sqft,Resale,Ready to Move,5 out of 13,Semi-Furnished,East,This affordable 2 BHK flat is situated along a...,"₹3,800 per sqft",₹44.6 Lac
3,2 BHK Apartment for Sale in Jahangirabad Surat,Carpet Area,700 sqft,New Property,Ready to Move,6 out of 14,Unfurnished,East,2 BHK Flat For sell IN Jahangirabad Prime Loca...,"₹3,966 per sqft",₹47 Lac
4,"2 BHK Apartment for Sale in Orchid Fantasia, P...",Super Area,1250 sqft,Orchid Fantasia,New Property,Unfurnished,2,2,"Multistorey Apartment for Sale in Palanpur, Su...","₹3,600 per sqft",₹45 Lac
5,"2 BHK Apartment for Sale in Anand Aspire, Jaha...",Super Area,1265 sqft,Unfurnished,Poss. by Dec '25,New Property,Anand Aspire,2,Multistorey Apartment for Sale in Jahangirabad...,"₹3,411 per sqft",₹43.2 Lac
6,3 BHK Villa for Sale in Dindoli Surat,Carpet Area,1404 sqft,Unfurnished,Poss. by Jun '24,New Property,East,Main Road,contraction,NaN,₹42.1 Lac
7,Office Space for Sale in Vesu Surat,Carpet Area,700 sqft,New Property,Poss. by Sep '25,7 out of 10,1,NaN,"best commercial for business ,investors ,busin...","₹3,392 per sqft",₹44.1 Lac
8,"2 BHK Apartment for Sale in Orchid Gardenia, P...",Super Area,1180 sqft,Orchid Gardenia,New Property,Unfurnished,2,2,"Multistorey Apartment for Sale in Palanpur, Su...","₹3,751 per sqft",₹44.3 Lac
9,2 BHK Apartment for Sale in Palanpur Surat,Carpet Area,720 sqft,New Property,Poss. by Dec '25,3 out of 14,Unfurnished,East,"Irrespective of the business branch, the our g...","₹3,200 per sqft",₹40 Lac

In [84]:
df.rename(columns = {"areaWithType":"Area Type"}, inplace=True)

In [85]:
df.head(5)

,property_name,Area Type,square_feet,transaction,status,floor,furnishing,facing,description,price_per_sqft,price
0,2 BHK Apartment for Sale in Dindoli Surat,Carpet Area,644 sqft,New Property,Poss. by Oct '24,5 out of 10,Unfurnished,West,"Luxury project with basement parking, Solar ro...","₹2,891 per sqft",₹33.8 Lac
1,2 BHK Apartment for Sale in Althan Surat,Super Area,1278 sqft,New Property,Poss. by Jan '26,6 out of 14,Unfurnished,South -West,2 And 3 BHK Luxurious Flat for Sell In New Alt...,"₹3,551 per sqft",₹45.4 Lac
2,2 BHK Apartment for Sale in Pal Gam Surat,Super Area,1173 sqft,Resale,Ready to Move,5 out of 13,Semi-Furnished,East,This affordable 2 BHK flat is situated along a...,"₹3,800 per sqft",₹44.6 Lac
3,2 BHK Apartment for Sale in Jahangirabad Surat,Carpet Area,700 sqft,New Property,Ready to Move,6 out of 14,Unfurnished,East,2 BHK Flat For sell IN Jahangirabad Prime Loca...,"₹3,966 per sqft",₹47 Lac
4,"2 BHK Apartment for Sale in Orchid Fantasia, P...",Super Area,1250 sqft,Orchid Fantasia,New Property,Unfurnished,2,2,"Multistorey Apartment for Sale in Palanpur, Su...","₹3,600 per sqft",₹45 Lac

In [86]:
df.rename(columns= {"price_per_sqft": "Price @_sqft"}, inplace= True)

In [87]:
df.head()

,property_name,Area Type,square_feet,transaction,status,floor,furnishing,facing,description,Price @_sqft,price
0,2 BHK Apartment for Sale in Dindoli Surat,Carpet Area,644 sqft,New Property,Poss. by Oct '24,5 out of 10,Unfurnished,West,"Luxury project with basement parking, Solar ro...","₹2,891 per sqft",₹33.8 Lac
1,2 BHK Apartment for Sale in Althan Surat,Super Area,1278 sqft,New Property,Poss. by Jan '26,6 out of 14,Unfurnished,South -West,2 And 3 BHK Luxurious Flat for Sell In New Alt...,"₹3,551 per sqft",₹45.4 Lac
2,2 BHK Apartment for Sale in Pal Gam Surat,Super Area,1173 sqft,Resale,Ready to Move,5 out of 13,Semi-Furnished,East,This affordable 2 BHK flat is situated along a...,"₹3,800 per sqft",₹44.6 Lac
3,2 BHK Apartment for Sale in Jahangirabad Surat,Carpet Area,700 sqft,New Property,Ready to Move,6 out of 14,Unfurnished,East,2 BHK Flat For sell IN Jahangirabad Prime Loca...,"₹3,966 per sqft",₹47 Lac
4,"2 BHK Apartment for Sale in Orchid Fantasia, P...",Super Area,1250 sqft,Orchid Fantasia,New Property,Unfurnished,2,2,"Multistorey Apartment for Sale in Palanpur, Su...","₹3,600 per sqft",₹45 Lac

In [88]:
# df.fillna(0)
# df.head(10)

In [89]:
df.head(10)

,property_name,Area Type,square_feet,transaction,status,floor,furnishing,facing,description,Price @_sqft,price
0,2 BHK Apartment for Sale in Dindoli Surat,Carpet Area,644 sqft,New Property,Poss. by Oct '24,5 out of 10,Unfurnished,West,"Luxury project with basement parking, Solar ro...","₹2,891 per sqft",₹33.8 Lac
1,2 BHK Apartment for Sale in Althan Surat,Super Area,1278 sqft,New Property,Poss. by Jan '26,6 out of 14,Unfurnished,South -West,2 And 3 BHK Luxurious Flat for Sell In New Alt...,"₹3,551 per sqft",₹45.4 Lac
2,2 BHK Apartment for Sale in Pal Gam Surat,Super Area,1173 sqft,Resale,Ready to Move,5 out of 13,Semi-Furnished,East,This affordable 2 BHK flat is situated along a...,"₹3,800 per sqft",₹44.6 Lac
3,2 BHK Apartment for Sale in Jahangirabad Surat,Carpet Area,700 sqft,New Property,Ready to Move,6 out of 14,Unfurnished,East,2 BHK Flat For sell IN Jahangirabad Prime Loca...,"₹3,966 per sqft",₹47 Lac
4,"2 BHK Apartment for Sale in Orchid Fantasia, P...",Super Area,1250 sqft,Orchid Fantasia,New Property,Unfurnished,2,2,"Multistorey Apartment for Sale in Palanpur, Su...","₹3,600 per sqft",₹45 Lac
5,"2 BHK Apartment for Sale in Anand Aspire, Jaha...",Super Area,1265 sqft,Unfurnished,Poss. by Dec '25,New Property,Anand Aspire,2,Multistorey Apartment for Sale in Jahangirabad...,"₹3,411 per sqft",₹43.2 Lac
6,3 BHK Villa for Sale in Dindoli Surat,Carpet Area,1404 sqft,Unfurnished,Poss. by Jun '24,New Property,East,Main Road,contraction,NaN,₹42.1 Lac
7,Office Space for Sale in Vesu Surat,Carpet Area,700 sqft,New Property,Poss. by Sep '25,7 out of 10,1,NaN,"best commercial for business ,investors ,busin...","₹3,392 per sqft",₹44.1 Lac
8,"2 BHK Apartment for Sale in Orchid Gardenia, P...",Super Area,1180 sqft,Orchid Gardenia,New Property,Unfurnished,2,2,"Multistorey Apartment for Sale in Palanpur, Su...","₹3,751 per sqft",₹44.3 Lac
9,2 BHK Apartment for Sale in Palanpur Surat,Carpet Area,720 sqft,New Property,Poss. by Dec '25,3 out of 14,Unfurnished,East,"Irrespective of the business branch, the our g...","₹3,200 per sqft",₹40 Lac

In [90]:
# df.fillna("0")
# df.head(10)

In [91]:
df.head(10)

,property_name,Area Type,square_feet,transaction,status,floor,furnishing,facing,description,Price @_sqft,price
0,2 BHK Apartment for Sale in Dindoli Surat,Carpet Area,644 sqft,New Property,Poss. by Oct '24,5 out of 10,Unfurnished,West,"Luxury project with basement parking, Solar ro...","₹2,891 per sqft",₹33.8 Lac
1,2 BHK Apartment for Sale in Althan Surat,Super Area,1278 sqft,New Property,Poss. by Jan '26,6 out of 14,Unfurnished,South -West,2 And 3 BHK Luxurious Flat for Sell In New Alt...,"₹3,551 per sqft",₹45.4 Lac
2,2 BHK Apartment for Sale in Pal Gam Surat,Super Area,1173 sqft,Resale,Ready to Move,5 out of 13,Semi-Furnished,East,This affordable 2 BHK flat is situated along a...,"₹3,800 per sqft",₹44.6 Lac
3,2 BHK Apartment for Sale in Jahangirabad Surat,Carpet Area,700 sqft,New Property,Ready to Move,6 out of 14,Unfurnished,East,2 BHK Flat For sell IN Jahangirabad Prime Loca...,"₹3,966 per sqft",₹47 Lac
4,"2 BHK Apartment for Sale in Orchid Fantasia, P...",Super Area,1250 sqft,Orchid Fantasia,New Property,Unfurnished,2,2,"Multistorey Apartment for Sale in Palanpur, Su...","₹3,600 per sqft",₹45 Lac
5,"2 BHK Apartment for Sale in Anand Aspire, Jaha...",Super Area,1265 sqft,Unfurnished,Poss. by Dec '25,New Property,Anand Aspire,2,Multistorey Apartment for Sale in Jahangirabad...,"₹3,411 per sqft",₹43.2 Lac
6,3 BHK Villa for Sale in Dindoli Surat,Carpet Area,1404 sqft,Unfurnished,Poss. by Jun '24,New Property,East,Main Road,contraction,NaN,₹42.1 Lac
7,Office Space for Sale in Vesu Surat,Carpet Area,700 sqft,New Property,Poss. by Sep '25,7 out of 10,1,NaN,"best commercial for business ,investors ,busin...","₹3,392 per sqft",₹44.1 Lac
8,"2 BHK Apartment for Sale in Orchid Gardenia, P...",Super Area,1180 sqft,Orchid Gardenia,New Property,Unfurnished,2,2,"Multistorey Apartment for Sale in Palanpur, Su...","₹3,751 per sqft",₹44.3 Lac
9,2 BHK Apartment for Sale in Palanpur Surat,Carpet Area,720 sqft,New Property,Poss. by Dec '25,3 out of 14,Unfurnished,East,"Irrespective of the business branch, the our g...","₹3,200 per sqft",₹40 Lac

In [92]:
df.head(10)

,property_name,Area Type,square_feet,transaction,status,floor,furnishing,facing,description,Price @_sqft,price
0,2 BHK Apartment for Sale in Dindoli Surat,Carpet Area,644 sqft,New Property,Poss. by Oct '24,5 out of 10,Unfurnished,West,"Luxury project with basement parking, Solar ro...","₹2,891 per sqft",₹33.8 Lac
1,2 BHK Apartment for Sale in Althan Surat,Super Area,1278 sqft,New Property,Poss. by Jan '26,6 out of 14,Unfurnished,South -West,2 And 3 BHK Luxurious Flat for Sell In New Alt...,"₹3,551 per sqft",₹45.4 Lac
2,2 BHK Apartment for Sale in Pal Gam Surat,Super Area,1173 sqft,Resale,Ready to Move,5 out of 13,Semi-Furnished,East,This affordable 2 BHK flat is situated along a...,"₹3,800 per sqft",₹44.6 Lac
3,2 BHK Apartment for Sale in Jahangirabad Surat,Carpet Area,700 sqft,New Property,Ready to Move,6 out of 14,Unfurnished,East,2 BHK Flat For sell IN Jahangirabad Prime Loca...,"₹3,966 per sqft",₹47 Lac
4,"2 BHK Apartment for Sale in Orchid Fantasia, P...",Super Area,1250 sqft,Orchid Fantasia,New Property,Unfurnished,2,2,"Multistorey Apartment for Sale in Palanpur, Su...","₹3,600 per sqft",₹45 Lac
5,"2 BHK Apartment for Sale in Anand Aspire, Jaha...",Super Area,1265 sqft,Unfurnished,Poss. by Dec '25,New Property,Anand Aspire,2,Multistorey Apartment for Sale in Jahangirabad...,"₹3,411 per sqft",₹43.2 Lac
6,3 BHK Villa for Sale in Dindoli Surat,Carpet Area,1404 sqft,Unfurnished,Poss. by Jun '24,New Property,East,Main Road,contraction,NaN,₹42.1 Lac
7,Office Space for Sale in Vesu Surat,Carpet Area,700 sqft,New Property,Poss. by Sep '25,7 out of 10,1,NaN,"best commercial for business ,investors ,busin...","₹3,392 per sqft",₹44.1 Lac
8,"2 BHK Apartment for Sale in Orchid Gardenia, P...",Super Area,1180 sqft,Orchid Gardenia,New Property,Unfurnished,2,2,"Multistorey Apartment for Sale in Palanpur, Su...","₹3,751 per sqft",₹44.3 Lac
9,2 BHK Apartment for Sale in Palanpur Surat,Carpet Area,720 sqft,New Property,Poss. by Dec '25,3 out of 14,Unfurnished,East,"Irrespective of the business branch, the our g...","₹3,200 per sqft",₹40 Lac

In [93]:
df.isnull().sum()
# df.head(10)
df.tail()

,property_name,Area Type,square_feet,transaction,status,floor,furnishing,facing,description,Price @_sqft,price
4520,6 BHK Apartment for Sale in Millionaires Lifes...,Carpet Area,2000 sqft,New Property,Poss. by Dec '26,5 out of 12,Unfurnished,South - East,"Check out Millionaires Lifestyle in Vesu, one ...",NaN,Call for Price
4521,"4 BHK Apartment for Sale in Savan Superia, Alt...",Super Area,3600 sqft,New Property,Poss. by Dec '25,5 out of 16,Unfurnished,South - East,Superia is a premium residential project launc...,NaN,Call for Price
4522,5 BHK Apartment for Sale in Roongta Green Vall...,Carpet Area,2250 sqft,New Property,Poss. by Dec '25,7 out of 13,Unfurnished,North - East,"When it comes to beautiful homes, nothing beat...",NaN,Call for Price
4523,"6 BHK Apartment for Sale in Cellestial Dreams,...",Carpet Area,3450 sqft,New Property,Ready to Move,7 out of 18,Unfurnished,North - West,"DRB Ravani Cellestial Dreams in Vesu, Surat is...",NaN,Call for Price
4524,4 BHK Apartment for Sale in Roongta Green Vall...,Super Area,4500 sqft,New Property,Ready to Move,3 out of 12,Unfurnished,North,Roongta Green Valley is one of the popular res...,NaN,Call for Price

In [94]:
df.head(10)

,property_name,Area Type,square_feet,transaction,status,floor,furnishing,facing,description,Price @_sqft,price
0,2 BHK Apartment for Sale in Dindoli Surat,Carpet Area,644 sqft,New Property,Poss. by Oct '24,5 out of 10,Unfurnished,West,"Luxury project with basement parking, Solar ro...","₹2,891 per sqft",₹33.8 Lac
1,2 BHK Apartment for Sale in Althan Surat,Super Area,1278 sqft,New Property,Poss. by Jan '26,6 out of 14,Unfurnished,South -West,2 And 3 BHK Luxurious Flat for Sell In New Alt...,"₹3,551 per sqft",₹45.4 Lac
2,2 BHK Apartment for Sale in Pal Gam Surat,Super Area,1173 sqft,Resale,Ready to Move,5 out of 13,Semi-Furnished,East,This affordable 2 BHK flat is situated along a...,"₹3,800 per sqft",₹44.6 Lac
3,2 BHK Apartment for Sale in Jahangirabad Surat,Carpet Area,700 sqft,New Property,Ready to Move,6 out of 14,Unfurnished,East,2 BHK Flat For sell IN Jahangirabad Prime Loca...,"₹3,966 per sqft",₹47 Lac
4,"2 BHK Apartment for Sale in Orchid Fantasia, P...",Super Area,1250 sqft,Orchid Fantasia,New Property,Unfurnished,2,2,"Multistorey Apartment for Sale in Palanpur, Su...","₹3,600 per sqft",₹45 Lac
5,"2 BHK Apartment for Sale in Anand Aspire, Jaha...",Super Area,1265 sqft,Unfurnished,Poss. by Dec '25,New Property,Anand Aspire,2,Multistorey Apartment for Sale in Jahangirabad...,"₹3,411 per sqft",₹43.2 Lac
6,3 BHK Villa for Sale in Dindoli Surat,Carpet Area,1404 sqft,Unfurnished,Poss. by Jun '24,New Property,East,Main Road,contraction,NaN,₹42.1 Lac
7,Office Space for Sale in Vesu Surat,Carpet Area,700 sqft,New Property,Poss. by Sep '25,7 out of 10,1,NaN,"best commercial for business ,investors ,busin...","₹3,392 per sqft",₹44.1 Lac
8,"2 BHK Apartment for Sale in Orchid Gardenia, P...",Super Area,1180 sqft,Orchid Gardenia,New Property,Unfurnished,2,2,"Multistorey Apartment for Sale in Palanpur, Su...","₹3,751 per sqft",₹44.3 Lac
9,2 BHK Apartment for Sale in Palanpur Surat,Carpet Area,720 sqft,New Property,Poss. by Dec '25,3 out of 14,Unfurnished,East,"Irrespective of the business branch, the our g...","₹3,200 per sqft",₹40 Lac

In [95]:
df.fillna({"Price @_sqft": "₹2,500per_sqrft"})
df.tail()

,property_name,Area Type,square_feet,transaction,status,floor,furnishing,facing,description,Price @_sqft,price
4520,6 BHK Apartment for Sale in Millionaires Lifes...,Carpet Area,2000 sqft,New Property,Poss. by Dec '26,5 out of 12,Unfurnished,South - East,"Check out Millionaires Lifestyle in Vesu, one ...",NaN,Call for Price
4521,"4 BHK Apartment for Sale in Savan Superia, Alt...",Super Area,3600 sqft,New Property,Poss. by Dec '25,5 out of 16,Unfurnished,South - East,Superia is a premium residential project launc...,NaN,Call for Price
4522,5 BHK Apartment for Sale in Roongta Green Vall...,Carpet Area,2250 sqft,New Property,Poss. by Dec '25,7 out of 13,Unfurnished,North - East,"When it comes to beautiful homes, nothing beat...",NaN,Call for Price
4523,"6 BHK Apartment for Sale in Cellestial Dreams,...",Carpet Area,3450 sqft,New Property,Ready to Move,7 out of 18,Unfurnished,North - West,"DRB Ravani Cellestial Dreams in Vesu, Surat is...",NaN,Call for Price
4524,4 BHK Apartment for Sale in Roongta Green Vall...,Super Area,4500 sqft,New Property,Ready to Move,3 out of 12,Unfurnished,North,Roongta Green Valley is one of the popular res...,NaN,Call for Price

In [96]:
df.isnull().sum()

property_name       0
Area Type           0
square_feet         0
transaction       104
status              1
floor              45
furnishing        340
facing            589
description      1371
Price @_sqft      368
price               0
dtype: int64

In [97]:
df.fillna({"Price @_sqft": "₹35000"}, inplace=True)

,property_name,Area Type,square_feet,transaction,status,floor,furnishing,facing,description,Price @_sqft,price
0,2 BHK Apartment for Sale in Dindoli Surat,Carpet Area,644 sqft,New Property,Poss. by Oct '24,5 out of 10,Unfurnished,West,"Luxury project with basement parking, Solar ro...","₹2,891 per sqft",₹33.8 Lac
1,2 BHK Apartment for Sale in Althan Surat,Super Area,1278 sqft,New Property,Poss. by Jan '26,6 out of 14,Unfurnished,South -West,2 And 3 BHK Luxurious Flat for Sell In New Alt...,"₹3,551 per sqft",₹45.4 Lac
2,2 BHK Apartment for Sale in Pal Gam Surat,Super Area,1173 sqft,Resale,Ready to Move,5 out of 13,Semi-Furnished,East,This affordable 2 BHK flat is situated along a...,"₹3,800 per sqft",₹44.6 Lac
3,2 BHK Apartment for Sale in Jahangirabad Surat,Carpet Area,700 sqft,New Property,Ready to Move,6 out of 14,Unfurnished,East,2 BHK Flat For sell IN Jahangirabad Prime Loca...,"₹3,966 per sqft",₹47 Lac
4,"2 BHK Apartment for Sale in Orchid Fantasia, P...",Super Area,1250 sqft,Orchid Fantasia,New Property,Unfurnished,2,2,"Multistorey Apartment for Sale in Palanpur, Su...","₹3,600 per sqft",₹45 Lac
...,...,...,...,...,...,...,...,...,...,...,...
4520,6 BHK Apartment for Sale in Millionaires Lifes...,Carpet Area,2000 sqft,New Property,Poss. by Dec '26,5 out of 12,Unfurnished,South - East,"Check out Millionaires Lifestyle in Vesu, one ...",₹35000,Call for Price
4521,"4 BHK Apartment for Sale in Savan Superia, Alt...",Super Area,3600 sqft,New Property,Poss. by Dec '25,5 out of 16,Unfurnished,South - East,Superia is a premium residential project launc...,₹35000,Call for Price
4522,5 BHK Apartment for Sale in Roongta Green Vall...,Carpet Area,2250 sqft,New Property,Poss. by Dec '25,7 out of 13,Unfurnished,North - East,"When it comes to beautiful homes, nothing beat...",₹35000,Call for Price
4523,"6 BHK Apartment for Sale in Cellestial Dreams,...",Carpet Area,3450 sqft,New Property,Ready to Move,7 out of 18,Unfurnished,North - West,"DRB Ravani Cellestial Dreams in Vesu, Surat is...",₹35000,Call for Price
4524,4 BHK Apartment for Sale in Roongta Green Vall...,Super Area,4500 sqft,New Property,Ready to Move,3 out of 12,Unfurnished,North,Roongta Green Valley is one of the popular res...,₹35000,Call for Price

In [98]:
df.isnull().sum()

property_name       0
Area Type           0
square_feet         0
transaction       104
status              1
floor              45
furnishing        340
facing            589
description      1371
Price @_sqft        0
price               0
dtype: int64

In [99]:
df.tail()

,property_name,Area Type,square_feet,transaction,status,floor,furnishing,facing,description,Price @_sqft,price
4520,6 BHK Apartment for Sale in Millionaires Lifes...,Carpet Area,2000 sqft,New Property,Poss. by Dec '26,5 out of 12,Unfurnished,South - East,"Check out Millionaires Lifestyle in Vesu, one ...",₹35000,Call for Price
4521,"4 BHK Apartment for Sale in Savan Superia, Alt...",Super Area,3600 sqft,New Property,Poss. by Dec '25,5 out of 16,Unfurnished,South - East,Superia is a premium residential project launc...,₹35000,Call for Price
4522,5 BHK Apartment for Sale in Roongta Green Vall...,Carpet Area,2250 sqft,New Property,Poss. by Dec '25,7 out of 13,Unfurnished,North - East,"When it comes to beautiful homes, nothing beat...",₹35000,Call for Price
4523,"6 BHK Apartment for Sale in Cellestial Dreams,...",Carpet Area,3450 sqft,New Property,Ready to Move,7 out of 18,Unfurnished,North - West,"DRB Ravani Cellestial Dreams in Vesu, Surat is...",₹35000,Call for Price
4524,4 BHK Apartment for Sale in Roongta Green Vall...,Super Area,4500 sqft,New Property,Ready to Move,3 out of 12,Unfurnished,North,Roongta Green Valley is one of the popular res...,₹35000,Call for Price

In [100]:
df.isnull().sum()

property_name       0
Area Type           0
square_feet         0
transaction       104
status              1
floor              45
furnishing        340
facing            589
description      1371
Price @_sqft        0
price               0
dtype: int64

In [101]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4525 entries, 0 to 4524
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   property_name  4525 non-null   str
 1   Area Type      4525 non-null   str
 2   square_feet    4525 non-null   str
 3   transaction    4421 non-null   str
 4   status         4524 non-null   str
 5   floor          4480 non-null   str
 6   furnishing     4185 non-null   str
 7   facing         3936 non-null   str
 8   description    3154 non-null   str
 9   Price @_sqft   4525 non-null   str
 10  price          4525 non-null   str
dtypes: str(11)
memory usage: 389.0 KB

In [102]:
new_df = df.drop(columns = ["property_name"])

In [103]:
new_df

,Area Type,square_feet,transaction,status,floor,furnishing,facing,description,Price @_sqft,price
0,Carpet Area,644 sqft,New Property,Poss. by Oct '24,5 out of 10,Unfurnished,West,"Luxury project with basement parking, Solar ro...","₹2,891 per sqft",₹33.8 Lac
1,Super Area,1278 sqft,New Property,Poss. by Jan '26,6 out of 14,Unfurnished,South -West,2 And 3 BHK Luxurious Flat for Sell In New Alt...,"₹3,551 per sqft",₹45.4 Lac
2,Super Area,1173 sqft,Resale,Ready to Move,5 out of 13,Semi-Furnished,East,This affordable 2 BHK flat is situated along a...,"₹3,800 per sqft",₹44.6 Lac
3,Carpet Area,700 sqft,New Property,Ready to Move,6 out of 14,Unfurnished,East,2 BHK Flat For sell IN Jahangirabad Prime Loca...,"₹3,966 per sqft",₹47 Lac
4,Super Area,1250 sqft,Orchid Fantasia,New Property,Unfurnished,2,2,"Multistorey Apartment for Sale in Palanpur, Su...","₹3,600 per sqft",₹45 Lac
...,...,...,...,...,...,...,...,...,...,...
4520,Carpet Area,2000 sqft,New Property,Poss. by Dec '26,5 out of 12,Unfurnished,South - East,"Check out Millionaires Lifestyle in Vesu, one ...",₹35000,Call for Price
4521,Super Area,3600 sqft,New Property,Poss. by Dec '25,5 out of 16,Unfurnished,South - East,Superia is a premium residential project launc...,₹35000,Call for Price
4522,Carpet Area,2250 sqft,New Property,Poss. by Dec '25,7 out of 13,Unfurnished,North - East,"When it comes to beautiful homes, nothing beat...",₹35000,Call for Price
4523,Carpet Area,3450 sqft,New Property,Ready to Move,7 out of 18,Unfurnished,North - West,"DRB Ravani Cellestial Dreams in Vesu, Surat is...",₹35000,Call for Price
4524,Super Area,4500 sqft,New Property,Ready to Move,3 out of 12,Unfurnished,North,Roongta Green Valley is one of the popular res...,₹35000,Call for Price

In [104]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4525 entries, 0 to 4524
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   property_name  4525 non-null   str
 1   Area Type      4525 non-null   str
 2   square_feet    4525 non-null   str
 3   transaction    4421 non-null   str
 4   status         4524 non-null   str
 5   floor          4480 non-null   str
 6   furnishing     4185 non-null   str
 7   facing         3936 non-null   str
 8   description    3154 non-null   str
 9   Price @_sqft   4525 non-null   str
 10  price          4525 non-null   str
dtypes: str(11)
memory usage: 389.0 KB

In [105]:
new_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4525 entries, 0 to 4524
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Area Type     4525 non-null   str
 1   square_feet   4525 non-null   str
 2   transaction   4421 non-null   str
 3   status        4524 non-null   str
 4   floor         4480 non-null   str
 5   furnishing    4185 non-null   str
 6   facing        3936 non-null   str
 7   description   3154 non-null   str
 8   Price @_sqft  4525 non-null   str
 9   price         4525 non-null   str
dtypes: str(10)
memory usage: 353.6 KB

In [106]:
dd = df.drop(columns=["square_feet"])

In [107]:
dd.info()

<class 'pandas.DataFrame'>
RangeIndex: 4525 entries, 0 to 4524
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   property_name  4525 non-null   str
 1   Area Type      4525 non-null   str
 2   transaction    4421 non-null   str
 3   status         4524 non-null   str
 4   floor          4480 non-null   str
 5   furnishing     4185 non-null   str
 6   facing         3936 non-null   str
 7   description    3154 non-null   str
 8   Price @_sqft   4525 non-null   str
 9   price          4525 non-null   str
dtypes: str(10)
memory usage: 353.6 KB

In [108]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4525 entries, 0 to 4524
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   property_name  4525 non-null   str
 1   Area Type      4525 non-null   str
 2   square_feet    4525 non-null   str
 3   transaction    4421 non-null   str
 4   status         4524 non-null   str
 5   floor          4480 non-null   str
 6   furnishing     4185 non-null   str
 7   facing         3936 non-null   str
 8   description    3154 non-null   str
 9   Price @_sqft   4525 non-null   str
 10  price          4525 non-null   str
dtypes: str(11)
memory usage: 389.0 KB

In [112]:
df.isnull().sum()

property_name       0
Area Type           0
square_feet         0
transaction       104
status              1
floor              45
furnishing        340
facing            589
description      1371
Price @_sqft        0
price               0
dtype: int64

In [113]:
new_DF =df.fillna({"description": "Everything is good and Well"},inplace=True)

In [117]:
new_DF.isnull().sum()

property_name      0
Area Type          0
square_feet        0
transaction      104
status             1
floor             45
furnishing       340
facing           589
description        0
Price @_sqft       0
price              0
dtype: int64

In [119]:
df.transaction.tail(20)

4505    New Property
4506    New Property
4507    New Property
4508    New Property
4509    New Property
4510    New Property
4511    New Property
4512    New Property
4513    New Property
4514    New Property
4515    New Property
4516          Resale
4517          Resale
4518    New Property
4519    New Property
4520    New Property
4521    New Property
4522    New Property
4523    New Property
4524    New Property
Name: transaction, dtype: str

In [ ]:
df.drop()