In [7]:
import pandas as pd
myset = {
    "name": ["adhish","Nirmal", "bishal"],
    "age": [19,21,22],
    "faculty": "BCA"
}
myvar = pd.DataFrame(myset)
print(myvar)

     name  age faculty
0  adhish   19     BCA
1  Nirmal   21     BCA
2  bishal   22     BCA

In [8]:
myvari = pd.Series(myset)
print(myvari)

name       [adhish, Nirmal, bishal]
age                    [19, 21, 22]
faculty                         BCA
dtype: object

In [9]:
df = pd.read_csv('unclean_data.csv')
print(df)

                                          property_name areaWithType  \
0             2 BHK Apartment for Sale in Dindoli Surat  Carpet Area
1              2 BHK Apartment for Sale in Althan Surat   Super Area
2             2 BHK Apartment for Sale in Pal Gam Surat   Super Area
3        2 BHK Apartment for Sale in Jahangirabad Surat  Carpet Area
4     2 BHK Apartment for Sale in Orchid Fantasia, P...   Super Area
...                                                 ...          ...
4520  6 BHK Apartment for Sale in Millionaires Lifes...  Carpet Area
4521  4 BHK Apartment for Sale in Savan Superia, Alt...   Super Area
4522  5 BHK Apartment for Sale in Roongta Green Vall...  Carpet Area
4523  6 BHK Apartment for Sale in Cellestial Dreams,...  Carpet Area
4524  4 BHK Apartment for Sale in Roongta Green Vall...   Super Area

     square_feet      transaction            status        floor  \
0       644 sqft     New Property  Poss. by Oct '24  5 out of 10
1      1278 sqft     New Property  Poss. by Jan '26  6 out of 14
2      1173 sqft           Resale     Ready to Move  5 out of 13
3       700 sqft     New Property     Ready to Move  6 out of 14
4      1250 sqft  Orchid Fantasia      New Property  Unfurnished
...          ...              ...               ...          ...
4520   2000 sqft     New Property  Poss. by Dec '26  5 out of 12
4521   3600 sqft     New Property  Poss. by Dec '25  5 out of 16
4522   2250 sqft     New Property  Poss. by Dec '25  7 out of 13
4523   3450 sqft     New Property     Ready to Move  7 out of 18
4524   4500 sqft     New Property     Ready to Move  3 out of 12

          furnishing        facing  \
0        Unfurnished          West
1        Unfurnished   South -West
2     Semi-Furnished          East
3        Unfurnished          East
4                  2             2
...              ...           ...
4520     Unfurnished  South - East
4521     Unfurnished  South - East
4522     Unfurnished  North - East
4523     Unfurnished  North - West
4524     Unfurnished         North

                                            description    price_per_sqft  \
0     Luxury project with basement parking, Solar ro...  ₹2,891 per sqft
1     2 And 3 BHK Luxurious Flat for Sell In New Alt...  ₹3,551 per sqft
2     This affordable 2 BHK flat is situated along a...  ₹3,800 per sqft
3     2 BHK Flat For sell IN Jahangirabad Prime Loca...  ₹3,966 per sqft
4     Multistorey Apartment for Sale in Palanpur, Su...  ₹3,600 per sqft
...                                                 ...               ...
4520  Check out Millionaires Lifestyle in Vesu, one ...               NaN
4521  Superia is a premium residential project launc...               NaN
4522  When it comes to beautiful homes, nothing beat...               NaN
4523  DRB Ravani Cellestial Dreams in Vesu, Surat is...               NaN
4524  Roongta Green Valley is one of the popular res...               NaN

               price
0         ₹33.8 Lac
1         ₹45.4 Lac
2         ₹44.6 Lac
3           ₹47 Lac
4           ₹45 Lac
...              ...
4520  Call for Price
4521  Call for Price
4522  Call for Price
4523  Call for Price
4524  Call for Price

[4525 rows x 11 columns]

In [10]:
df.head()

,property_name,areaWithType,square_feet,transaction,status,floor,furnishing,facing,description,price_per_sqft,price
0,2 BHK Apartment for Sale in Dindoli Surat,Carpet Area,644 sqft,New Property,Poss. by Oct '24,5 out of 10,Unfurnished,West,"Luxury project with basement parking, Solar ro...","₹2,891 per sqft",₹33.8 Lac
1,2 BHK Apartment for Sale in Althan Surat,Super Area,1278 sqft,New Property,Poss. by Jan '26,6 out of 14,Unfurnished,South -West,2 And 3 BHK Luxurious Flat for Sell In New Alt...,"₹3,551 per sqft",₹45.4 Lac
2,2 BHK Apartment for Sale in Pal Gam Surat,Super Area,1173 sqft,Resale,Ready to Move,5 out of 13,Semi-Furnished,East,This affordable 2 BHK flat is situated along a...,"₹3,800 per sqft",₹44.6 Lac
3,2 BHK Apartment for Sale in Jahangirabad Surat,Carpet Area,700 sqft,New Property,Ready to Move,6 out of 14,Unfurnished,East,2 BHK Flat For sell IN Jahangirabad Prime Loca...,"₹3,966 per sqft",₹47 Lac
4,"2 BHK Apartment for Sale in Orchid Fantasia, P...",Super Area,1250 sqft,Orchid Fantasia,New Property,Unfurnished,2,2,"Multistorey Apartment for Sale in Palanpur, Su...","₹3,600 per sqft",₹45 Lac

In [ ]:
df.columns

In [ ]:
df.sample(2) #Shows the random Rows values

In [ ]:
df.info()  #Shows the infor.. about DataFrame

In [41]:
# my_Sts = pd.DataFrame()
df.describe() #shows Statistical

,property_name,areaWithType,square_feet,transaction,status,floor,furnishing,facing,description,price_per_sqft,price
count,4525,4525,4525,4421,4524,4480,4185,3936,3154,4157,4525
unique,1992,6,1399,38,138,222,78,176,2588,2134,841
top,3 BHK Apartment for Sale in Vesu Surat,Super Area,1000 sqft,Resale,Ready to Move,Resale,Unfurnished,East,Multistorey apartment is available for sale. I...,"₹5,000 per sqft",Call for Price
freq,93,2599,77,2197,3078,431,2322,1487,35,64,173

In [42]:
df.shape #shows rows and Columns

(4525, 11)

In [43]:
df.columns #shows column names

Index(['property_name', 'areaWithType', 'square_feet', 'transaction', 'status',
       'floor', 'furnishing', 'facing', 'description', 'price_per_sqft',
       'price'],
      dtype='str')

In [44]:
df.index #shows rows index

RangeIndex(start=0, stop=4525, step=1)

In [45]:
df.dtypes #data types

property_name     str
areaWithType      str
square_feet       str
transaction       str
status            str
floor             str
furnishing        str
facing            str
description       str
price_per_sqft    str
price             str
dtype: object

In [46]:
len(df) #number of rows

4525

In [47]:
df["property_name"] #gives value with duplicate values

0               2 BHK Apartment for Sale in Dindoli Surat
1                2 BHK Apartment for Sale in Althan Surat
2               2 BHK Apartment for Sale in Pal Gam Surat
3          2 BHK Apartment for Sale in Jahangirabad Surat
4       2 BHK Apartment for Sale in Orchid Fantasia, P...
                              ...
4520    6 BHK Apartment for Sale in Millionaires Lifes...
4521    4 BHK Apartment for Sale in Savan Superia, Alt...
4522    5 BHK Apartment for Sale in Roongta Green Vall...
4523    6 BHK Apartment for Sale in Cellestial Dreams,...
4524    4 BHK Apartment for Sale in Roongta Green Vall...
Name: property_name, Length: 4525, dtype: str

In [49]:
df["property_name"].value_counts(4000) #without Duplicate value

property_name
3 BHK Apartment for Sale in Vesu Surat                              0.020552
3 BHK Apartment for Sale in Pal Surat                               0.016796
3 BHK Apartment for Sale in Palanpur Surat                          0.013702
4 BHK Apartment for Sale in Vesu Surat                              0.012376
2 BHK Apartment for Sale in Palanpur Surat                          0.011934
                                                                      ...
4 BHK Apartment for Sale in Universal Homes, Adajan Surat           0.000221
4 BHK Apartment for Sale in D and M Elysium Avenue, Piplod Surat    0.000221
5 BHK Apartment for Sale in Sangini Arise, Bharthana Surat          0.000221
5 BHK Apartment for Sale in D and M Elysium Avenue, Piplod Surat    0.000221
6 BHK Apartment for Sale in Millionaires Lifestyle, Vesu Surat      0.000221
Name: proportion, Length: 1992, dtype: float64

In [50]:
df["description"].value_counts()

description
Multistorey apartment is available for sale. It is a good location property. Please contact for more details.Read more                                                                                                                                                                                                                                                                                                                                                                                                                                                                         35
Luxurious 3 Bhk Flat For Sell In Vesu                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          14
location                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       13
he beautifully designed granite flooring enhances the beauty of the flat. Moreover, this property offers close proximity to important landmarks such as close to mall, , and close to school. Many of the modern amenities being offered, like swimming pool, cctv surveillance, club house  community center, fitness centre  gym, park, lifts, maintenance staff and visitor parking, will provide a pleasant living experience for you. This residential project ensures a 247 water supply for its residents.Read more                                                                     11
Altra Luxurious 3 Bhk Flat For Sell In Vesu                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    11
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ..
Check out Millionaires Lifestyle in Vesu, one of the upcoming underconstruction housing societies in Surat. There are apartments for sale in Millionaires Lifestyle.Read more                                                                                                                                                                                                                                                                                                                                                                                                                   1
Superia is a premium residential project launched by construction firm Savan Infraavenue in Althan, Surat. The project will be built on an area of 1.7 acres and is offering beautiful and comfortable 4 BHK apartments for sale. Carpet area of 4 BHK apartments is in the range of 1486 to 1776 sq ft. Amenities available for the convenience of residents are car parking areas, landscaped gardens, swimming pool, gymnasium, party hall, library, childrens play area, banquet hall, indoor games, spa and sauna facility, and other facilities are provided in the complex.Read more     1
When it comes to beautiful homes, nothing beats us. With our appealing 45 BHK flats, enjoy the beauty of living life the luxurious way. Along with being located in the heart of the city, we are ecoconscious and believe in promoting an ecofriendly lifestyle.Read more                                                                                                                                                                                                                                                                                                                      1
DRB Ravani Cellestial Dreams in Vesu, Surat is a ready to move housing society. It offers apartments in varied budget range. These units are a perfect combination of comfort and style, specifically designed to suit your requirements and conveniences. There are 5BHK apartments available in this project.Read more                                                                                                                                                                                                                                                                        1
Roongta Green Valley is one of the popular residential project in Vesu, Surat. It has lavish yet thoughtfully designed 8 Towers and 208 residences.::::Status::::Under Construction::::Possession by::::Apr 24::::Total Units::::208::::Total Towers::::8::::Project Area::::3 Acre::::Full Address::::Ashirwad Society, Bharthana, Surat, Gujarat::::Pincode::::395003Read more                                                                                                                                                                                                                1
Name: count, Length: 2588, dtype: int64

In [54]:
df.iloc[2,4]

'Ready to Move'

In [55]:
df.isnull()

,property_name,areaWithType,square_feet,transaction,status,floor,furnishing,facing,description,price_per_sqft,price
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
4520,False,False,False,False,False,False,False,False,False,True,False
4521,False,False,False,False,False,False,False,False,False,True,False
4522,False,False,False,False,False,False,False,False,False,True,False
4523,False,False,False,False,False,False,False,False,False,True,False
4524,False,False,False,False,False,False,False,False,False,True,False

In [56]:
df.notnull()

,property_name,areaWithType,square_feet,transaction,status,floor,furnishing,facing,description,price_per_sqft,price
0,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...
4520,True,True,True,True,True,True,True,True,True,False,True
4521,True,True,True,True,True,True,True,True,True,False,True
4522,True,True,True,True,True,True,True,True,True,False,True
4523,True,True,True,True,True,True,True,True,True,False,True
4524,True,True,True,True,True,True,True,True,True,False,True

In [ ]:
df["property_name"].unique() #view Unique value

<StringArray>
[                       '2 BHK Apartment for Sale in Dindoli Surat',
                         '2 BHK Apartment for Sale in Althan Surat',
                        '2 BHK Apartment for Sale in Pal Gam Surat',
                   '2 BHK Apartment for Sale in Jahangirabad Surat',
      '2 BHK Apartment for Sale in Orchid Fantasia, Palanpur Surat',
     '2 BHK Apartment for Sale in Anand Aspire, Jahangirabad Surat',
                            '3 BHK Villa for Sale in Dindoli Surat',
                            '  Office Space for Sale in Vesu Surat',
      '2 BHK Apartment for Sale in Orchid Gardenia, Palanpur Surat',
                       '2 BHK Apartment for Sale in Palanpur Surat',
 ...
        '3 BHK Apartment for Sale in KPM Terra Prime, Piplod Surat',
       '4 BHK Apartment for Sale in Milestone Palacio, Athwa Surat',
        '4 BHK Apartment for Sale in KPM Terra Prime, Piplod Surat',
          '4 BHK Apartment for Sale in Rajhans Altezza, Vesu Surat',
        '5 BHK Apartment for Sale in KPM Terra Prime, Piplod Surat',
        '4 BHK Apartment for Sale in Universal Homes, Adajan Surat',
 '4 BHK Apartment for Sale in D and M Elysium Avenue, Piplod Surat',
       '5 BHK Apartment for Sale in Sangini Arise, Bharthana Surat',
 '5 BHK Apartment for Sale in D and M Elysium Avenue, Piplod Surat',
   '6 BHK Apartment for Sale in Millionaires Lifestyle, Vesu Surat']
Length: 1992, dtype: str

In [58]:
df["price_per_sqft"].unique()

<StringArray>
['₹2,891 per sqft ', '₹3,551 per sqft ', '₹3,800 per sqft ',
 '₹3,966 per sqft ', '₹3,600 per sqft ', '₹3,411 per sqft ',
                nan, '₹3,392 per sqft ', '₹3,751 per sqft ',
 '₹3,200 per sqft ',
 ...
 '₹5,487 per sqft ', '₹7,300 per sqft ', '₹6,040 per sqft ',
 '₹6,811 per sqft ', '₹5,930 per sqft ', '₹7,470 per sqft ',
 '₹8,018 per sqft ', '₹8,512 per sqft ', '₹8,200 per sqft ',
 '₹5,756 per sqft ']
Length: 2135, dtype: str

In [ ]:
df["square_feet"].nunique() #Count unique values

1399

In [60]:
df["property_name"].nunique()

1992

In [61]:
df["property_name"].value_counts() #Count occurrences of each value

property_name
3 BHK Apartment for Sale in Vesu Surat                              93
3 BHK Apartment for Sale in Pal Surat                               76
3 BHK Apartment for Sale in Palanpur Surat                          62
4 BHK Apartment for Sale in Vesu Surat                              56
2 BHK Apartment for Sale in Palanpur Surat                          54
                                                                    ..
4 BHK Apartment for Sale in Universal Homes, Adajan Surat            1
4 BHK Apartment for Sale in D and M Elysium Avenue, Piplod Surat     1
5 BHK Apartment for Sale in Sangini Arise, Bharthana Surat           1
5 BHK Apartment for Sale in D and M Elysium Avenue, Piplod Surat     1
6 BHK Apartment for Sale in Millionaires Lifestyle, Vesu Surat       1
Name: count, Length: 1992, dtype: int64